export const ActionTypes = {
  TOGGLE_SHOW_RESULTS: 'TOGGLE_SHOW_RESULTS',
  TOGGLE_SHOW_CUSTOM_HAND: 'TOGGLE_SHOW_CUSTOM_HAND',
  GET_NEW_CARDS: 'GET_NEW_CARDS',
  GET_NEW_DECK: 'GET_NEW_DECK',
  SORT_HAND: 'SORT_HAND',
  CHANGE_HAND: 'CHANGE_HAND'
}
