export const ActionTypes = {
  TOGGLE_SHOW_RESULTS: 'TOGGLE_SHOW_RESULTS',
  TOGGLE_SHOW_CUSTOM_HAND: 'TOGGLE_SHOW_CUSTOM_HAND',
  TOGGLE_HIDE_RESULTS_WHEN_DEALT: 'TOGGLE_HIDE_RESULTS_WHEN_DEALT',
  GET_NEW_CARDS: 'GET_NEW_CARDS',
  GET_NEW_DECK: 'GET_NEW_DECK',
  SORT_HAND: 'SORT_HAND',
  CHANGE_HAND: 'CHANGE_HAND',
  SHOW_ERROR: 'SHOW_ERROR'
}
